[tool.poetry]
name = "sentinel-platform"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["Du Yuyang <du.r.yuyang@gmail.com>"]
dependencies = {}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
