apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-monitor
  namespace: monitoring
  labels:
    release: prometheus # This label is critical! It tells Prometheus to pick this up.
spec:
  selector:
    matchLabels:
      ray.io/cluster: sentinel-training-cluster
  namespaceSelector:
    matchNames:
    - sentinel-prod
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
